### PR TITLE
Support optional dependencies

### LINKED ISSUE #39: Optional dependencies
They should be installed when possible.

### PR DESCRIPTION
**Pull request by zkochan**
close #39

### CODE REVIEW

**Comment by rstacruz** [comment]
Looks good! Great work. Thank you for your contribution. 💚

**Comment by rstacruz** [comment]
Lemme add you to the collaborators. Thanks for all your help. https://github.com/rstacruz/collaborative-etiquette#for-collaborators

**Comment by zkochan** [comment]
Awesome! Thanks!

**Comment by iamstarkov** [comment]
awesome

**Pull request merged**
