### PR TITLE
Added npm badge to README.md

### PR DESCRIPTION
**Pull request by furqanZafar**
Added npm badge to README.md. Can't wait till 1.0.0 :)

Thanks! :+1:

### CODE REVIEW

**Comment by rstacruz** [comment]
Curious: do people actually care about version badges?

**Comment by rstacruz** [comment]
Thanks!

**Comment by rstacruz** [comment]
okay i've no idea why travis is broken, i swear it was fxed when i went to sleep haha

**Comment by furqanZafar** [comment]
easier to track progress with npm badge i guess, the day it says 1.0.0, everyone would switch to it :)

**Pull request merged**
