### PR TITLE
Using TypeScript for static typing

### PR DESCRIPTION
**Pull request by zkochan**
I used TS because I have more experience with it, if someone will want to rewrite it to flow, I'll have no objections.

ref #347 

Still need to add a lot of types... I'll make the TypeScript configuration more strict once all the types will be there

### CODE REVIEW

**Comment by zkochan** [comment]
Wow, this line of code was so hard for me to understand:

```js
if (err || srcPath === linkString) return cb(err)
```
> from [here](https://github.com/rstacruz/pnpm/blob/v0.31.2/lib/fs/force_symlink.js#L20-L27)

It can be both an error and a success!

**Comment by rstacruz** [comment]
> if (err || srcPath === linkString) return cb(err)

Normally I write `if (x || y)` to mean: if `x`, or if it's not `x` but `y`...

In this case, it's like:

> If it's an error...
> ...or if it's not an error, but `srcPath === linkString`...

Or more like:

> Consider `srcPath === linkString` an error

But I can't actually remember what went on here, sorry :P

**Comment by rstacruz** [comment]
Oh alright, that wasn't _entirely_ true, I think what happened here is:

```js
    fs.readlink(dstPath, (err, linkString) => {
      if (err || srcPath === linkString) return cb(err)
```

pseudo code translation:

- check out `dstPath`
- if we get an error, throw an error
- if it's a symlink to the correct path already (`srcPath`), it's a success

**Comment by zkochan** [comment]
In the end I've figured out the logic. Here's the outcome after the rewrite:

```ts
export default async function forceSymlink (srcPath: string, dstPath: string, type: SymlinkType) {
  debug(`${srcPath} -> ${dstPath}`)
  try {
    fs.symlinkSync(srcPath, dstPath, type)
    return
  } catch (err) {
    if ((<NodeJS.ErrnoException>err).code !== 'EEXIST') throw err

    const linkString = await fs.readlink(dstPath)
    if (srcPath === linkString) {
      return
    }
    await fs.unlink(dstPath)
    await forceSymlink(srcPath, dstPath, type)
  }
}
```

**Comment by zkochan** [comment]
The thing that confused me was that even on success, `err` is passed to `cb`. But the err is not defined on success. It was just visually confusing :smile:

**Comment by zkochan** [comment]
By the way, this is not ready for merge yet. I have broken some logic with the last commit.
Till the `refactor(*.ts): use async/await` commit it is fine. The last commit I will fix in the evening. And I guess I'll work on even stricter rules in a separate pull request. To turn on TypeScript's `strictNullChecks`

**Comment by iamstarkov** [comment]
> `+4,518 −1,386`

huge job ✨

**Pull request merged**
