### PR TITLE
feat(network): support all the npm's proxy/ssl configs

### LINKED ISSUE #373: The strict-ssl config is ignored
### Expected behavior:

Everything good.

### Actual behavior:

"strict-ssl=false" in .npmrc or /users/.npmrc ignored at all and "Unable to verify certificate error".

### PR DESCRIPTION
**Pull request by zkochan**
Close #373

### CODE REVIEW

**Comment by zkochan** [comment]
This one is very straightforward. I am going to merge it and publish with the prune feature

**Comment by zkochan** [comment]
@iamstarkov what do you think?

**Comment by iamstarkov** [comment]
@zkochan approved 👍

**Comment by zkochan** [comment]
Such a big luck that we recently switched to npm-registry-client from got+retry.

**Pull request merged**
