### PR TITLE
Support ignore-sripts

### PR DESCRIPTION
**Pull request by ratson**

### CODE REVIEW

**Comment by iamstarkov** [comment]
what are the ignore-scripts?

**Comment by ratson** [comment]
From https://github.com/npm/npm/blob/master/doc/cli/npm-install.md
> The --ignore-scripts argument will cause npm to not execute any scripts defined in the package.json. See npm-scripts(7).

**Comment by rstacruz** [comment]
Thanks! That's reasonable.

**Comment by rstacruz** [comment]
still need to add it to --help though

**Pull request merged**
