### PR TITLE
Add a public API

### LINKED ISSUE #125: Add a public API for installation and linking
I am using pnpm as part of a mono repo and I need to install a subset of the package.json files. Something like `pnpm install -f package.local.json`. Since files are not supported, I looked at integration within my own CLI tool. These are the problems I ran into:

```javascript
const install = require('pnpm/lib/cmd/install');
const installError = require('pnpm/lib/err');

return install(dependencies, { quiet: false }).catch(installError);
```

On the surface, this looks pretty good, but it unfortunately uses the `package.json` from the current directory of my CLI tool as root, so it installs them in the wrong location.

```javascript
const install = require('pnpm/lib/install_multiple');
const installConfig = require('pnpm/lib/config');
const installLog = require('pnpm/lib/logger');
const installError = require('pnpm/lib/err');
const installPeers = require('pnpm/lib/install/link_peers');

const ctx = {
  root: rootPath,
  store: path.resolve(rootPath, installConfig.store_path),
  log: installLog()
};
    
return install(ctx, dependencies, path.join(ctx.root, 'node_modules'), { quiet: false })
  .then(_ => installPeers(null, ctx.store, ctx.installs))
  .catch(installError);
```

This did the trick, but as you can see its pretty verbose and reaches quite a bit into the `pnpm` internals. It would be nice to have a public API that could do something like this:

```javascript
import pnpmApi from 'pnpm/api';

return pnpmApi.install(dependencies, rootPath, { quiet: false });
```

The implementation would look like my last snippet above. Let me know if you would accept a pull request for this?

EDIT: Also wanted to point out that `installPeers` accepts `pkg` as a first argument, but it does not use it in the function.

### PR DESCRIPTION
**Pull request by zkochan**
close #125

### CODE REVIEW

**Comment by zkochan** [comment]
I am also thinking about making `options.quiet=true` by default, when using the API. It

**Comment by davej** [comment]
Any particular reason why this wasn't merged or was it just out of scope?

**Comment by zkochan** [comment]
yes, it was. I thought it would figure out after an amend. But anyway, with this commit it was added 46bcdac831903b365c98f5311aac9955e3c59c0e

For some reason though, the API page did not appear on the gh pages documentation site :confused:

**Comment by rstacruz** [comment]
is it time to make a new pnpm release? :-)

**Comment by zkochan** [comment]
I think so :-)

**Pull request closed without merging**
