### PR TITLE
Create pnpm-debug.log file on fail

### PR DESCRIPTION
**Pull request by zkochan**
I created a custom logger for this feature (please review it as well [@zkochan/logger](https://github.com/zkochan/logger)). If it is fine, I'll transfer it to the pnpm organization.

The main idea is to use a logger which emits events with the logging info. The file logger records all the different logging levels. The progress logger listens only the `progress` type.

Also I substituted the debug usages with @zkochan/logger usages. But I did not remove debug, it listens now for debug logging events.

Example output: https://gist.github.com/zkochan/272e4c60eb3248373c63af9bc2db8924

### CODE REVIEW

**Comment by zkochan** [comment]
I am merging it because I have to create a new pull request based on these changes.

But I'll be more then happy to make updates if someone will have comments.

**Comment by iamstarkov** [comment]
Looks good

**Comment by iamstarkov** [comment]
Just one question: why do we log only progress events?

**Comment by zkochan** [comment]
We don't log progress events. They are not useful.

**Comment by zkochan** [comment]
I mean the progress events that log download percentage

**Comment by iamstarkov** [comment]
ok, got it. thanks

**Pull request merged**
